In [47]:
import numpy as np
import pyqtgraph as pg
from PyQt6 import QtGui, QtCore
from PyQt6.QtWidgets import QDockWidget, QWidget, QMainWindow
import PyQt6

In [51]:
image=np.eye(3)
print(image)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
win = pg.GraphicsLayoutWidget()
plot1 = pg.PlotItem()
img = pg.ImageItem( image, levels=(0,1) )
tr = QtGui.QTransform()  # prepare ImageItem transformation:
tr.scale(6.0, 3.0)       # scale horizontal and vertical axes
tr.translate(-1.5, -1.5) # move 3x3 image to locate center at axis origin
img.setTransform(tr)
plot1.addItem( img )  # add ImageItem to PlotItem
plot1.showAxes(True)  # frame it with a full set of axes
plot1.invertY(True)   # vertical axis counts top to bottom
print(plot1)

In [58]:
main = QMainWindow()
win = pg.GraphicsView()
win.setCentralItem(img)
#win.show()
#widget = pg.PlotWidget()
#widget.addItem(img)
#main = QDockWidget("Testing Window")
#popwidget = QWidget()
#popwidget.setLayou
main.setCentralWidget(win)
main.show()

RuntimeError: wrapped C/C++ object of type ImageItem has been deleted